using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace GymMamagementSystemRivas
{
    public partial class clientDashboard : Form
    {
        private string _username;

        // default constructor generated by designer
        public clientDashboard()
        {
            InitializeComponent();
        }

        public clientDashboard(string username) : this()
        {
            _username = username;
            // if there is a label to show username, try to set it
            try
            {
                var lbl = this.Controls.Find("lblUsername", true);
                if (lbl.Length > 0 && lbl[0] is Label usernameLabel)
                    usernameLabel.Text = _username;
            }
            catch { }
        }
        // load event handler referenced by designer
        private void clientDashboard_Load(object sender, EventArgs e)
        {
            // optional client dashboard initialization
        }
    }
}
